import os
SECRET_KEY = 'the beijing telecom research center'
SQLALCHEMY_DATABASE_URI= 'sqlite:///db.sqlite'
# SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:123456@localhost:3306/cowrest'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
# SQLALCHEMY_POOL_SIZE=5
# SQLALCHEMY_POOL_TIMEOUT=10
base_images_path=os.path.join(os.path.dirname(os.path.abspath(__file__)) ,r"test")
# base_images_path = 'f:/test_flask'
# base_images_path = 'd:/cowrest_test'
batch_size = 100
model = None
classes = []
img_size = (299, 299)
noveltyDetectionLayerName = "fc1"
noveltyDetectionLayerSize = 1024
isCenterLoss = None
isTripletLoss = None
min_predict = 95.00
max_video_size=20000