SECRET_KEY = 'the beijing telecom research center'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
# SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:123456@localhost:3306/cowrest'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
app.config.base_images_path = 'f:/test_flask'
# base_images_path = 'd:/cowrest_test'
batch_size = 100
model = None
classes = []
img_size = (299, 299)
noveltyDetectionLayerName = "fc1"
noveltyDetectionLayerSize = 1024
isCenterLoss = None
isTripletLoss = None
min_predict = 95.00
